export const SELECT_MEAL = 'SELECT_MEAL';
export const BEGIN_CREATING_MEAL = 'BEGIN_CREATING_MEAL';
export const SUCCESS_CREATING_MEAL = 'SUCCESS_CREATING_MEAL';
export const ERROR_CREATING_MEAL = 'ERROR_CREATING_MEAL';
